### ISSUE TITLE
Not working Godaddy office 365

### ISSUE THREAD

**Issue by Nature101** [BakkerJan/evilginx3#1]
it's not working with godaddy office365 webmail
here's the error
: 2023/06/26 11:46:40 [133] WARN: Cannot handshake client www.office.com EOF
2023/06/26 11:46:40 [132] WARN: Cannot handshake client www.office.com EOF
2023/06/26 11:46:49 [135] WARN: Cannot handshake client www.office.com EOF
2023/06/26 11:46:49 [134] WARN: Cannot handshake client www.office.com EOF
2023/06/26 11:48:22 [137] WARN: Cannot handshake client login.microsoftonline.com tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
2023/06/26 11:48:24 [136] WARN: Cannot handshake client login.microsoftonline.com EOF
2023/06/26 11:48:26 [138] WARN: Cannot handshake client login.microsoftonline.com tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9])
2023/06/26 11:48:28 [139] WARN: Cannot handshake client login.microsoftonline.com EOF
2023/06/26 11:48:36 [140] WARN: Cannot handshake client login.microsoftonline.com EOF
2023/06/26 11:48:36 [141] WARN: Cannot handshake client login.microsoftonline.com EOF
2023/06/26 11:48:39 [142] WARN: Cannot handshake client login.microsoftonline.com EOF
2023/06/26 11:48:39 [143] WARN: Cannot handshake client login.microsoftonline.com EOF

**Comment by BakkerJan** [comment]
@Nature101 I'm not sure if this is related to the phishlet. It seems Go/SSL related. 
Please make sure GO is updated, and renew the SSL certificates 

https://help.evilginx.com/docs/guides/config#certificates

**Comment by Nature101** [comment]
![image_2023-06-29_13-56-36](https://github.com/BakkerJan/evilginx3/assets/107625480/9934643e-7da6-4e44-a3a7-b5773a6346b8)
Its not working if the office 365 is from godaddy

**Comment by Dazmed707** [comment]
i have goodaddy phislet with office 365, send me dm in telegram.
@NDLR7
