### ISSUE TITLE
Google Phishlet?

### ISSUE THREAD

**Issue by Dazmed707** [BakkerJan/evilginx3#2]
Google Phishlet Available?

**Comment by BakkerJan** [comment]
I would suggest to take the course: https://academy.breakdev.org/evilginx-mastery/12wvr
That will teach you how to built phishlets.

**Comment by Dazmed707** [comment]
Yes, I already have the course and Google Phishlet working, thank you.

**Comment by Dazmed707** [comment]
need bypass red screen (safe browser chrome), any method available for this.

**Comment by BakkerJan** [comment]
@Dazmed707 Yes, take a look at this: https://www.jackphilipbutton.com/post/how-to-protect-evilginx-using-cloudflare-and-html-obfuscation

**Comment by Dazmed707** [comment]
Yes, I had read it, but I don't know how safe it is to implement it, I need something for at least 6 months for a red team attack, I am thinking of adding this implementation as well.
https://github.com/waelmas/frameless-bitb

**Comment by whithey79** [comment]
@Dazmed707 good day, would you be able to share your google phishlets?

**Comment by Dazmed707** [comment]
> @Dazmed707 good day, would you be able to share your google phishlets?

only sell
