### ISSUE TITLE
session cookie not found: 

### ISSUE THREAD

**Issue by Orbior** [BakkerJan/evilginx3#3]
Hello Jan,

I tried your tutorial using this o365.yaml, however when I open the phishinglink o365 starts to auto login. Then nothing happens and a regular login screen appears. When I tried to put in some credentials there I get the following error page: invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

In Evilginx I get the following warning: 
[war] session cookie not found: 

I added some screenshots to clarify. What could be the issue?
![2024-01-24 11_37_11-Aanmelden bij uw account – Mozilla Firefox](https://github.com/BakkerJan/evilginx3/assets/59564285/3eb452c1-7339-47f6-89f4-a5ac52837f23)
![2024-01-24 11_37_27-Aanmelden bij uw account – Mozilla Firefox](https://github.com/BakkerJan/evilginx3/assets/59564285/c42f7fb8-3d5a-47e4-9242-2b63b8ac264b)
![2024-01-24 11_37_42-Microsoft-account – Mozilla Firefox](https://github.com/BakkerJan/evilginx3/assets/59564285/cd69f114-860f-433f-af31-84904d730914)
![2024-01-24 11_37_53-Window](https://github.com/BakkerJan/evilginx3/assets/59564285/e4a2b71a-d846-4380-86db-91250a1c1f41)

**Comment by BakkerJan** [comment]
@Orbior please hit me up at info [at] janbakker.tech, so we can exchange contact info for chat. 

I just tested your URL, and it seems to work fine on my end.

**Comment by Orbior** [comment]
I used wrong credentials to test. Seems to be working.

**Comment by BakkerJan** [comment]
@Orbior Okay, good luck. 
Let me know if you need help.
