### ISSUE TITLE
Completely broken Microsoft Phishlets (due to new update)

### ISSUE THREAD

**Issue by SupFeder** [BakkerJan/evilginx3#8]
Please for the love of FAQ fix it

**Comment by BakkerJan** [comment]
What's the error you're facing?

**Comment by SupFeder** [comment]
when I open the page and put the email in it i get: This login.registeringencrypted.com page can’t be found

**Comment by SupFeder** [comment]
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by BakkerJan** [comment]
I assume this is not related to the phishlet, as I just tested at my end. Works fine. 
Think it's DNS related.

**Comment by SupFeder** [comment]
Then how da frick I fix It, why you devs are all so sketchy?

**Comment by SupFeder** [comment]
Listen you know those micro365 and Outlook Phishlets you made? It May be the update but they directly redirect to the home Page without any cookies grabbing

**Comment by BakkerJan** [comment]
Please follow the docs, or take the course. 

https://help.evilginx.com/docs/intro
https://academy.breakdev.org/evilginx-mastery/12wvr

**Comment by SupFeder** [comment]
I would honestly take It if that russian bastard didn't put It for 400 bucks

**Comment by SupFeder** [comment]
Listen why no One wants to Aid someone Who Just needs a string of code?

**Comment by ademarc6969** [comment]
because chances are if you can't get a phishlet to work and are asking in a github issue, you're probably not using evilginx for the right reasons
